# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(default='missing_value', max_length=20, unique=True, verbose_name='Document ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nickname'),
        ),
    ]
